[tool.black]
line-length = 88
target-version = ["py38", "py39", "py310", "py311"]
include = "\.pyi?$"

[tool.flake8]
max-line-length = 88
extend-ignore = "E203,W503,F401,F811,F841,W293"
exclude = ".git,__pycache__,build,dist,.venv,venv"
